// @ts-nocheck
// eslint-disable
// This file is generated by create-validator-ts
import Ajv from 'ajv';
import * as apiTypes from './index';

export const SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/A",
    "definitions": {
        "A": {
            "type": "number"
        }
    }
};
const ajv = new Ajv({ removeAdditional: true }).addSchema(SCHEMA, "SCHEMA");
export function validateA(payload: unknown): apiTypes.A {
  /** Schema is defined in {@link SCHEMA.definitions.A } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/A");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid A: ' + ajv.errorsText(validator.errors, {dataVar: "A"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isA(payload: unknown): payload is apiTypes.A {
  try {
    validateA(payload);
    return true;
  } catch (error) {
    return false;
  }
}
