name: test
on:
  push:

permissions:
  contents: read
jobs:
  npm-6:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [14,16,18]
        os: [macOS-latest, windows-latest, ubuntu-latest]
    name: "npm 6, Node.js: ${{ matrix.node-version }} OS: ${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3
      - name: "Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable npm
      - run: npm install -g npe && npe packageManager "npm@6.14.16"
      - run: npm install
      - run: npm test
      - run: npm run test-npx
  npm-8:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        fail-fast: false
        node-version: [14,16,18]
        os: [macOS-latest, windows-latest, ubuntu-latest]
    name: "npm 8, Node:${{ matrix.node-version }} OS: ${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3
      - name: "Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable npm
      - run: npm install -g npe && npe packageManager "npm@8.19.1"
      - run: npm install
      - run: npm test
      - run: npm run test-npx
